import type { Produce, Order } from '@/types';

export const produce: Produce[] = [
  // Fresh Vegetables
  {
    id: '1',
    name: 'Organic Tomatoes',
    price: 120,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=500&h=500&fit=crop',
    category: 'Vegetables',
    description: 'Premium organic tomatoes, vine-ripened for the perfect balance of sweetness and acidity.',   
  },
  {
    id: '2',
    name: 'Fresh Spinach',
    price: 80,
    unit: 'bunch',
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=500&h=500&fit=crop',
    category: 'Vegetables',
    description: 'Crisp, nutrient-rich spinach leaves, perfect for salads and cooking.',
  },
  {
    id: '3',
    name: 'English Cucumbers',
    price: 60,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=500&h=500&fit=crop',
    category: 'Vegetables',
    description: 'Fresh, crunchy cucumbers ideal for salads and healthy snacking.',
  },
  {
    id: '4',
    name: 'Bell Peppers Mix',
    price: 150,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=500&h=500&fit=crop',
    category: 'Vegetables',
    description: 'Vibrant mix of red, yellow, and green bell peppers, rich in vitamins.',
  },
  {
    id: '5',
    name: 'Baby Carrots',
    price: 90,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1445282768818-728615cc910a?w=500&h=500&fit=crop',
    category: 'Vegetables',
    description: 'Sweet, tender baby carrots perfect for snacking and cooking.',
  },
  {
    id: '6',
    name: 'Broccoli Crown',
    price: 110,
    unit: 'piece',
    imageUrl: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=500&h=500&fit=crop',
    category: 'Vegetables',
    description: 'Fresh broccoli crowns, packed with nutrients and perfect for steaming.',
  },

  // Fresh Fruits
  {
    id: '7',
    name: 'Premium Avocados',
    price: 200,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=500&h=500&fit=crop',
    category: 'Fruits',
    description: 'Perfectly ripe avocados, creamy texture ideal for toast and salads.',
  },
  {
    id: '8',
    name: 'Organic Bananas',
    price: 70,
    unit: 'dozen',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=500&h=500&fit=crop',
    category: 'Fruits',
    description: 'Naturally sweet organic bananas, great for smoothies and snacking.',
  },
  {
    id: '9',
    name: 'Fresh Strawberries',
    price: 300,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=500&h=500&fit=crop',
    category: 'Fruits',
    description: 'Juicy, sweet strawberries perfect for desserts and breakfast.',
  },
  {
    id: '10',
    name: 'Green Apples',
    price: 180,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=500&h=500&fit=crop',
    category: 'Fruits',
    description: 'Crisp and tart green apples, perfect for baking and snacking.',
  },
  {
    id: '11',
    name: 'Orange Varieties',
    price: 100,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1557800636-894a64c1696f?w=500&h=500&fit=crop',
    category: 'Fruits',
    description: 'Sweet and juicy oranges, rich in vitamin C and perfect for juice.',
  },
  {
    id: '12',
    name: 'Mixed Berries',
    price: 400,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1498557850523-fd3d118b962e?w=500&h=500&fit=crop',
    category: 'Fruits',
    description: 'Premium mix of blueberries, raspberries, and blackberries.',
  },

  // Dairy & Eggs
  {
    id: '13',
    name: 'Farm Fresh Eggs',
    price: 120,
    unit: 'dozen',
    imageUrl: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=500&h=500&fit=crop',
    category: 'Dairy & Eggs',
    description: 'Free-range eggs from local farms, rich in protein and nutrients.',
  },
  {
    id: '14',
    name: 'Organic Milk',
    price: 80,
    unit: 'liter',
    imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=500&h=500&fit=crop',
    category: 'Dairy & Eggs',
    description: 'Pure organic milk from grass-fed cows, rich and creamy.',
  },
  {
    id: '15',
    name: 'Greek Yogurt',
    price: 150,
    unit: 'pack',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=500&h=500&fit=crop',
    category: 'Dairy & Eggs',
    description: 'Thick, creamy Greek yogurt packed with probiotics and protein.',
  },
  {
    id: '16',
    name: 'Artisan Cheese',
    price: 350,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=500&h=500&fit=crop',
    category: 'Dairy & Eggs',
    description: 'Handcrafted artisan cheese with rich, complex flavors.',
  },

  // Pantry Essentials
  {
    id: '17',
    name: 'Organic Honey',
    price: 250,
    unit: 'jar',
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=500&h=500&fit=crop',
    category: 'Pantry Essentials',
    description: 'Pure organic honey from local beekeepers, unprocessed and natural.',
  },
  {
    id: '18',
    name: 'Extra Virgin Olive Oil',
    price: 400,
    unit: 'bottle',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=500&h=500&fit=crop',
    category: 'Pantry Essentials',
    description: 'Cold-pressed extra virgin olive oil, perfect for cooking and salads.',
  },
  {
    id: '19',
    name: 'Quinoa Seeds',
    price: 180,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=500&h=500&fit=crop',
    category: 'Pantry Essentials',
    description: 'Protein-rich quinoa seeds, a versatile superfood for healthy meals.',
  },
  {
    id: '20',
    name: 'Almonds Premium',
    price: 600,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1529258283598-8d6fe60b27f4?w=500&h=500&fit=crop',
    category: 'Pantry Essentials',
    description: 'Premium quality almonds, rich in healthy fats and protein.',
  },
];

// Sample orders data
export const orders: Order[] = [
  {
    id: 'ORD001',
    items: [
      { 
        id: '1', 
        name: 'Fresh Tomatoes', 
        quantity: 2, 
        price: 40,
        unit: 'kg',
        imageUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?auto=format&fit=crop&q=80&w=500&h=500',
        category: 'Vegetables',
        description: 'Fresh red tomatoes perfect for curries, dal, and Indian cooking.'
      },
      { 
        id: '2', 
        name: 'Onions', 
        quantity: 3, 
        price: 30,
        unit: 'kg',
        imageUrl: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&q=80&w=500&h=500',
        category: 'Vegetables',
        description: 'Essential red onions for Indian cooking, sabzi, and curries.'
      },
    ],
    total: 170,
    status: 'Delivered',
    date: '2024-01-15',
    estimatedDelivery: '2024-01-16',
  },
  {
    id: 'ORD002',
    items: [
      { 
        id: '21', 
        name: 'Mangoes (Alphonso)', 
        quantity: 1, 
        price: 300,
        unit: 'kg',
        imageUrl: 'https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?auto=format&fit=crop&q=80&w=500&h=500',
        category: 'Fruits',
        description: 'Premium Alphonso mangoes, the king of fruits in India.'
      },
      { 
        id: '54', 
        name: 'Basmati Rice', 
        quantity: 2, 
        price: 120,
        unit: 'kg',
        imageUrl: 'https://images.unsplash.com/photo-1536304993881-ff6e9eefa2a6?auto=format&fit=crop&q=80&w=500&h=500',
        category: 'Pantry Essentials',
        description: 'Premium basmati rice perfect for biryanis and pulao.'
      },
    ],
    total: 540,
    status: 'Processing',
    date: '2024-01-20',
    estimatedDelivery: '2024-01-22',
  },
  {
    id: 'ORD003',
    items: [
      { 
        id: '40', 
        name: 'Paneer', 
        quantity: 1, 
        price: 300,
        unit: 'kg',
        imageUrl: 'https://images.unsplash.com/photo-1559181567-c3190ca9959b?auto=format&fit=crop&q=80&w=500&h=500',
        category: 'Dairy & Eggs',
        description: 'Fresh homemade paneer perfect for Indian curries and dishes.'
      },
      { 
        id: '55', 
        name: 'Wheat Flour (Atta)', 
        quantity: 5, 
        price: 40,
        unit: 'kg',
        imageUrl: 'https://images.unsplash.com/photo-1574323347407-f5e1ad6d020b?auto=format&fit=crop&q=80&w=500&h=500',
        category: 'Pantry Essentials',
        description: 'Fresh wheat flour (atta) for rotis, parathas, and Indian breads.'
      },
    ],
    total: 500,
    status: 'Processing',
    date: '2024-01-18',
    estimatedDelivery: '2024-01-20',
  },
];
