import type { Produce, Order } from '@/types';

export const produce: Produce[] = [
  // Fresh Vegetables
  {
    id: '1',
    name: 'Organic Tomatoes',
    price: 120,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1592841200221-a6898f307baa?w=400&h=400&fit=crop&auto=format',
    category: 'Vegetables',
    description: 'Premium organic tomatoes, vine-ripened for the perfect balance of sweetness and acidity.',
  },
  {
    id: '2',
    name: 'Fresh Spinach',
    price: 80,
    unit: 'bunch',
    imageUrl: 'https://images.unsplash.com/photo-1576045057995-568f588f82fb?w=400&h=400&fit=crop&auto=format',
    category: 'Vegetables',
    description: 'Crisp, nutrient-rich spinach leaves, perfect for salads and cooking.',
  },
  {
    id: '3',
    name: 'English Cucumbers',
    price: 60,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1449300079323-02e209d9d3a6?w=400&h=400&fit=crop&auto=format',
    category: 'Vegetables',
    description: 'Fresh, crunchy cucumbers ideal for salads and healthy snacking.',
  },
  {
    id: '4',
    name: 'Bell Peppers Mix',
    price: 150,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1563565375-f3fdfdbefa83?w=400&h=400&fit=crop&auto=format',
    category: 'Vegetables',
    description: 'Vibrant mix of red, yellow, and green bell peppers, rich in vitamins.',
  },
  {
    id: '5',
    name: 'Baby Carrots',
    price: 90,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1445282768818-728615cc910a?w=400&h=400&fit=crop&auto=format',
    category: 'Vegetables',
    description: 'Sweet, tender baby carrots perfect for snacking and cooking.',
  },
  {
    id: '6',
    name: 'Broccoli Crown',
    price: 110,
    unit: 'piece',
    imageUrl: 'https://images.unsplash.com/photo-1459411621453-7b03977f4bfc?w=400&h=400&fit=crop&auto=format',
    category: 'Vegetables',
    description: 'Fresh broccoli crowns, packed with nutrients and perfect for steaming.',
  },

  // Fresh Fruits
  {
    id: '7',
    name: 'Premium Avocados',
    price: 200,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1523049673857-eb18f1d7b578?w=400&h=400&fit=crop&auto=format',
    category: 'Fruits',
    description: 'Perfectly ripe avocados, creamy texture ideal for toast and salads.',
  },
  {
    id: '8',
    name: 'Organic Bananas',
    price: 70,
    unit: 'dozen',
    imageUrl: 'https://images.unsplash.com/photo-1571771894821-ce9b6c11b08e?w=400&h=400&fit=crop&auto=format',
    category: 'Fruits',
    description: 'Naturally sweet organic bananas, great for smoothies and snacking.',
  },
  {
    id: '9',
    name: 'Fresh Strawberries',
    price: 300,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1464965911861-746a04b4bca6?w=400&h=400&fit=crop&auto=format',
    category: 'Fruits',
    description: 'Juicy, sweet strawberries perfect for desserts and breakfast.',
  },
  {
    id: '10',
    name: 'Green Apples',
    price: 180,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?w=400&h=400&fit=crop&auto=format',
    category: 'Fruits',
    description: 'Crisp and tart green apples, perfect for baking and snacking.',
  },
  {
    id: '11',
    name: 'Orange Varieties',
    price: 100,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1557800636-894a64c1696f?w=400&h=400&fit=crop&auto=format',
    category: 'Fruits',
    description: 'Sweet and juicy oranges, rich in vitamin C and perfect for juice.',
  },
  {
    id: '12',
    name: 'Mixed Berries',
    price: 400,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1506905925346-21bda4d32df4?w=400&h=400&fit=crop&auto=format',
    category: 'Fruits',
    description: 'Premium mix of blueberries, raspberries, and blackberries.',
  },

  // Dairy & Eggs
  {
    id: '13',
    name: 'Farm Fresh Eggs',
    price: 120,
    unit: 'dozen',
    imageUrl: 'https://images.unsplash.com/photo-1482049016688-2d3e1b311543?w=400&h=400&fit=crop&auto=format',
    category: 'Dairy',
    description: 'Free-range eggs from local farms, rich in protein and nutrients.',
  },
  {
    id: '14',
    name: 'Organic Milk',
    price: 80,
    unit: 'liter',
    imageUrl: 'https://images.unsplash.com/photo-1563636619-e9143da7973b?w=400&h=400&fit=crop&auto=format',
    category: 'Dairy',
    description: 'Pure organic milk from grass-fed cows, rich and creamy.',
  },
  {
    id: '15',
    name: 'Greek Yogurt',
    price: 150,
    unit: 'pack',
    imageUrl: 'https://images.unsplash.com/photo-1488477181946-6428a0291777?w=400&h=400&fit=crop&auto=format',
    category: 'Dairy',
    description: 'Thick, creamy Greek yogurt packed with probiotics and protein.',
  },
  {
    id: '16',
    name: 'Artisan Cheese',
    price: 350,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1452195100486-9cc805987862?w=400&h=400&fit=crop&auto=format',
    category: 'Dairy',
    description: 'Handcrafted artisan cheese with rich, complex flavors.',
  },

  // Pantry Essentials
  {
    id: '17',
    name: 'Organic Honey',
    price: 250,
    unit: 'jar',
    imageUrl: 'https://images.unsplash.com/photo-1587049352846-4a222e784d38?w=400&h=400&fit=crop&auto=format',
    category: 'Pantry',
    description: 'Pure organic honey from local beekeepers, unprocessed and natural.',
  },
  {
    id: '18',
    name: 'Extra Virgin Olive Oil',
    price: 400,
    unit: 'bottle',
    imageUrl: 'https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?w=400&h=400&fit=crop&auto=format',
    category: 'Pantry',
    description: 'Cold-pressed extra virgin olive oil, perfect for cooking and salads.',
  },
  {
    id: '19',
    name: 'Quinoa Seeds',
    price: 180,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1586201375761-83865001e31c?w=400&h=400&fit=crop&auto=format',
    category: 'Pantry',
    description: 'Protein-rich quinoa seeds, a versatile superfood for healthy meals.',
  },
  {
    id: '20',
    name: 'Almonds Premium',
    price: 600,
    unit: 'kg',
    imageUrl: 'https://images.unsplash.com/photo-1508747708059-e2ca90515cbb?w=400&h=400&fit=crop&auto=format',
    category: 'Pantry',
    description: 'Premium quality almonds, rich in healthy fats and protein.',
  },
];


export const orders: Order[] = [
  {
    id: 'FF1024',
    date: '2024-07-20',
    status: 'Out for Delivery',
    estimatedDelivery: 'Today, 4:30 PM',
    items: [
      {
        id: '1', name: 'Fresh Mangoes', price: 150, quantity: 2, imageUrl: 'https://picsum.photos/400/301',
        unit: '',
        category: '',
        description: ''
      },
      {
        id: '3', name: 'Paneer', price: 400, quantity: 1, imageUrl: 'https://picsum.photos/400/303',
        unit: '',
        category: '',
        description: ''
      },
    ],
    total: 700,
  },
  {
    id: 'FF1023',
    date: '2024-07-15',
    status: 'Delivered',
    estimatedDelivery: 'July 15, 2024',
    items: [
      {
        id: '2', name: 'Okra (Bhindi)', price: 60, quantity: 1, imageUrl: 'https://picsum.photos/400/302',
        unit: '',
        category: '',
        description: ''
      },
    ],
    total: 60,
  },
];
